In [ ]:
import keras
from numpy import array
import pandas as pd
from keras.preprocessing.text import Tokenizer
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding

In [ ]:
data = pd.read_csv('1661-0.txt', sep="\t")
#txt=read_
print(data)

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(data)
encoded_data= tokenizer.texts_to_sequences(data)[0]
encoded_data


In [ ]:
size=len(tokenizer.word_index)+1
print(size)

In [ ]:
sequences=list()
for j in range(1, len(encoded_data)):
    seq=encoded_data[j-1:j+1]
    sequences.append(seq)
print(len(sequences))


input and an output word ,i.e first word and predicted word are indexed as follows

In [105]:
sequences

[[1, 2],
 [2, 3],
 [3, 4],
 [4, 5],
 [5, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [10, 11]]

Split the sequence

In [106]:
sequences=array(sequences)
X,y=sequences[:,0],sequences[:,1]

In [107]:
X[:6]

array([1, 2, 3, 4, 5, 6])

In [108]:
y[:6]

array([2, 3, 4, 5, 6, 7])

One hot encoding


In [109]:
y=to_categorical(y,num_classes=size)
y[:6]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)

In [173]:
from tensorflow.keras.layers import *
from tensorflow.keras.models import *


model= Sequential()




model.add(Embedding(2557, 64, input_length=1, embeddings_initializer='glorot_uniform'))
#model.add(Reshape((64,)))
#model.add(Reshape((64,), input_shape=(94556, 1)))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
#model.add(Embedding(size,10,input_length=1))
model.add(LSTM(50))
model.add(Dense(size,activation="softmax"))
model.add(Dense(12, input_dim=7, activation='relu'))
print(model.summary())


Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_14 (Embedding)     (None, 1, 64)             163648    
_________________________________________________________________
lstm_10 (LSTM)               (None, 50)                23000     
_________________________________________________________________
dense_9 (Dense)              (None, 12)                612       
_________________________________________________________________
dense_10 (Dense)             (None, 12)                156       
Total params: 187,416
Trainable params: 187,416
Non-trainable params: 0
_________________________________________________________________
None


In [174]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
#comile the network

In [175]:
model.fit(X,y,epochs=50)
#fit network

Epoch 1/50
1/1 [==============================] - 5s 5s/step - loss: 10.4216 - accuracy: 0.1000
Epoch 2/50
1/1 [==============================] - 0s 13ms/step - loss: 10.4029 - accuracy: 0.1000
Epoch 3/50
1/1 [==============================] - 0s 17ms/step - loss: 10.3862 - accuracy: 0.1000
Epoch 4/50
1/1 [==============================] - 0s 21ms/step - loss: 10.3712 - accuracy: 0.1000
Epoch 5/50
1/1 [==============================] - 0s 7ms/step - loss: 10.3575 - accuracy: 0.1000
Epoch 6/50
1/1 [==============================] - 0s 22ms/step - loss: 10.3451 - accuracy: 0.1000
Epoch 7/50
1/1 [==============================] - 0s 14ms/step - loss: 10.3338 - accuracy: 0.1000
Epoch 8/50
1/1 [==============================] - 0s 16ms/step - loss: 10.3233 - accuracy: 0.1000
Epoch 9/50
1/1 [==============================] - ETA: 0s - loss: 10.3136 - accuracy: 0.100 - 0s 31ms/step - loss: 10.3136 - accuracy: 0.1000
Epoch 10/50
1/1 [==============================] - 0s 16ms/step - loss: 10.30

In [ ]:
import numpy as np
from tensorflow.keras.models import load_model

def generate_seq(model,tokenizer, enter_text, n_pred):
    in_text, result= enter_text, enter_text#
    for _ in range(n_pred):
        encoded= tokenizer.texts_to_sequences([in_text])
        encoded= np.array(encoded)
        
        #guess=model.predict_classes(encoded)
        #y_pred = model.predict(encoded)
        #y_pred = np.round(y_pred).astype(int)
        y_pred=np.argmax(model.predict(encoded))
        #predict_x=model.predict(encoded)
        #classes_x=np.argmax(predict_x,axis=1)
        #predictions = model.predict(encoded, verbose=1)
        out_word=""
        for word, index in tokenizer.word_index.items():
            if index == y_pred:
                out_word=word
                break
        #in_text, result= out_word,result+ "" +out_word
        print(out_word)
        return result


In [ ]:
while(True):
    
    text = input("Enter your line: ")
  
    if text == "0":
        print("Execution completed.....")
        break
  
    else:
        try:
            text = text.split(" ")
            text = text[-3:]
            print(text)
        
            generate_seq(model, tokenizer, enter_text,n_pred)
          
        except Exception as e:
            print("Error occurred: ",e)
            continue